---
title: "Auditory Distance Perception Study Power Analysis"
author: "Lucas Gonzalez - Damian Payo - Manuel Eguia"
date: "26/9/2023"
output:
  html_document:
    code_folding: "hide"
    theme: paper
    highlight: pygments
    toc: true
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(here)
library(ggplot2)
library(plotrix)
#library(segmented)
library(Routliers)
library(tidyverse)
library(ggpubr)
library(car)
library(data.table)
library(lme4)
library(nlme)
library(emmeans)
library(sjstats)
library(lmerTest)
library(MuMIn)
#library(nortest)
#library(effects)
```

# Fuente para los gráficos
```{r}
library(showtext)
font_add(family = "Times", regular = "TIMES.ttf")
showtext_auto()

theme_set(theme_bw(base_family = "Times"))
update_geom_defaults(
  geom = "text",
  aes(family = "Times")
)
```
## Carga de data

```{r, include=FALSE}
dir <- "./Data"

archivos_csv <- list.files(path = dir, pattern = "\\.csv$", full.names = TRUE)

for (archivo in archivos_csv) {
  nombre <- tools::file_path_sans_ext(basename(archivo))
  file <- read.csv(archivo, header = TRUE )
  assign(nombre, file)  # crea un data frame con ese nombre
}

rm(dir, file, nombre)
```

# Binaural_level + DRR
Columnas: WW - LL - WL - LW
```{r}
colnames(Binaural_level) <- c("WW","LL","WL","LW")

Distance <- c(1.5,2,2.5,3.3,4.3,5.6,7.2,9.4,12,15.5,20,26)
Binaural_level <- cbind(Binaural_level, Distance) %>%
  pivot_longer(cols = c("WW","LL","WL","LW"),
               names_to = "Condition",
               values_to = "Value" )
rm(Distance)
```

```{r}
cols <- c("#00AF55", "#EF0000", "#DB9501","#890070")
plot_BL <- Binaural_level %>%  ggplot(aes(x= Distance, 
                               y = Value, color = Condition)) +
  geom_line(linewidth = 0.5,alpha = 0.8) +
  #geom_abline(slope = 0, intercept = 0, linetype = "dashed", color = "black")+
  geom_point(alpha = 0.8, size = 3) +
  scale_y_continuous(breaks = c(0,-2,-4,-6,-8,-10,-12,-14,-16))+
  scale_x_log10(breaks = c(0,2,5,10,15,20,25))+
  scale_color_manual(values = cols,
                    limits = c('WW', 'LL', 'WL', 'LW'), 
                    labels = c('Wide', 'Low', 'Wide-Low', 'Low-Wide'))+
  theme_bw() +
  labs(x='Distance (m)', y='Binaural Level (dB)',tag ="(a)",
       color = NULL) +
  theme_bw()+
  theme(text = element_text(family = "Times",colour="black"),
        axis.title.x = element_text(size = 12,colour="black"),
        axis.title.y = element_text(size = 12,colour="black"),
        axis.text.x = element_text(size = 11,colour="black"),
        axis.text.y = element_text(size = 11,colour="black"),
        legend.text = element_text(size=12,colour="black"),
        legend.title = element_text(size=12,colour="black"),
        plot.title = element_text(size = 12, hjust = 0.5,colour="black"),
        #legend.box.background = element_rect(colour = "black"),
        #panel.grid = element_line(color= NA),
        legend.position = "Top")

```
```{r}
colnames(DRR) <- c("WW","LL","WL","LW")

Distance <- c(1.5,2,2.5,3.3,4.3,5.6,7.2,9.4,12,15.5,20,26)
DRR <- cbind(DRR, Distance) %>%
  pivot_longer(cols = c("WW","LL","WL","LW"),
               names_to = "Condition",
               values_to = "Value" )
rm(Distance)
```
```{r}
cols <- c("#00AF55", "#EF0000", "#DB9501","#890070")
plot_DRR <- DRR %>%  ggplot(aes(x= Distance, 
                               y = Value, color = Condition)) +
  geom_line(linewidth = 0.5,alpha = 0.8) +
  #geom_abline(slope = 0, intercept = 0, linetype = "dashed", color = "black")+
  geom_point(alpha = 0.8, size = 3) +
  scale_y_continuous(breaks = c(10,5,0,-5,-10,-10,-15,-20))+
  scale_x_log10(breaks = c(0,2,5,10,15,20,25))+
  scale_color_manual(values = cols,
                    limits = c('WW', 'LL', 'WL', 'LW'), 
                    labels = c('Wide', 'Low', 'Wide-Low', 'Low-Wide'))+
  theme_bw() +
  labs(x='Distance (m)', y='DRR (dB)', tag ="(b)",
       color = NULL) +
  theme_bw()+
  theme(text = element_text(family = "Times",colour="black"),
        axis.title.x = element_text(size = 12,colour="black"),
        axis.title.y = element_text(size = 12,colour="black"),
        axis.text.x = element_text(size = 11,colour="black"),
        axis.text.y = element_text(size = 11,colour="black"),
        #legend.text = element_text(size=12,colour="black"),
        #legend.title = element_text(size=12,colour="black"),
        plot.title = element_text(size = 12, hjust = 0.5,colour="black"),
        #legend.box.background = element_rect(colour = "black"),
        #panel.grid = element_line(color= NA),
        legend.position = "none")

```
```{r}
ggarrange(plot_BL,plot_DRR,nrow =2, common.legend = TRUE)


```

Figura 4 BL + DRR
```{r}
ggsave(plot = last_plot(),
  file = "BL_DRR.eps",
  device = cairo_ps,
  width = 1400,
  height = 1600,
  unit = "px",
  dpi = 300)

```

Fig 5 Spectro D VS R



### 1K Data_prom tibble with means and std per condition

```{r, warning=FALSE, error=FALSE}

data_prom <- data_clean %>% filter(is_outlier==FALSE) %>%
  group_by(condicion, distancia) %>%
  summarise(distancia,
            respuesta,
            prom_resp = mean(respuesta), 
            sd_log = sd(respuesta), 
            std_log = std.error(respuesta))

dist_curves <- ggplot(data_prom,
       aes(x=log(distancia), y=log(prom_resp),
           color = condicion)) +
  geom_point(alpha = 0.8) +
  geom_line(linewidth = 0.5,alpha = 0.8) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "black")+
  scale_x_continuous(breaks=log(c(1.5,2,2.5,3.3,4.3,5.6,7.2,9.4,12,15.5,20,26)),
                     labels=c(1.5,2,2.5,3.3,4.3,5.6,7.2,9.4,12,15.5,20,26))+
  scale_y_continuous(breaks=log(c(0.7,1,1.5,2,2.5,3.3,4.3,5.6,7.2,9.4,12,15.5,20,26,34,45)),
                     labels=c(0.7,1,1.5,2,2.5,3.3,4.3,5.6,7.2,9.4,12,15.5,20,26,34,45),
                     limits=c(log(1.5),log(30))
                     )+
  scale_color_manual(values = cols,
                    limits = c('WW', 'LL', 'WL', 'LW'), 
                    labels = c('Wide', 'Low', 'Wide-Low', 'Low-Wide'))+
  geom_errorbar(aes(ymin=log(prom_resp-std_log),
                    ymax=log(prom_resp+std_log)),
                width = 0.02,alpha = 0.8) +
  # facet_grid(rows = vars(ID)) +
  labs(title = "Cutoff Frequency: 1 kHz", x='Distance [log(m)]', y='Responses [log(m)]',
       color ="Condition", tag="(a)") +
  theme_bw()+
  theme(text = element_text(family = "Times",colour="black"),
        axis.title.x = element_text(size = 12,colour="black"),
        axis.title.y = element_text(size = 12,colour="black"),
        axis.text.x = element_text(size = 11,colour="black"),
        axis.text.y = element_text(size = 11,colour="black"),
        legend.text = element_text(size=12,colour="black"),
        legend.title = element_text(size=12,colour="black"),
        plot.title = element_text(size = 12, hjust = 0.5,colour="black"),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"),
        panel.grid = element_line(color= NA),
        legend.position = c(0.8, 0.22))

dist_curves
```


```{r}
# 1. Importar los archivos

# 2. Verificar nombres de columnas para identificar la frecuencia de 3 kHz
colnames(spectrum_low_direct)  # confirmá que "3.17480" está acá

# 3. Extraer la columna correspondiente a 3 kHz (3.17480) y renombrarla para facilitar
direct_LL_3k <- spectrum_low_direct %>% 
  select("X3.17480") %>% rename(direct = "X3.17480")
reverb_LL_3k <- spectrum_low_reverberant %>% 
  select("X3.17480") %>% rename(reverb = "X3.17480")


direct_WW_3k <- spectrum_wide_direct %>% 
  select("X3.17480") %>% rename(direct = "X3.17480")
reverb_WW_3k <- spectrum_wide_reverberant %>% 
  select("X3.17480") %>% rename(reverb = "X3.17480")


direct_LW_3k <- spectrum_lowwide_direct %>%
  select("X3.17480") %>% rename(direct = "X3.17480")
reverb_LW_3k <- spectrum_lowwide_reverberant %>% 
  select("X3.17480") %>% rename(reverb = "X3.17480")


direct_WL_3k <- spectrum_widelow_direct %>% 
  select("X3.17480") %>% rename(direct = "X3.17480")
reverb_WL_3k <- spectrum_widelow_reverberant %>%
  select("X3.17480") %>% rename(reverb = "X3.17480")
# 4. Calcular DRR (direct - reverb) en dB


drr_df_LL <- data.frame(condicion = "LL",
  log_distancia = log(c(1.5, 2, 2.5, 3.3, 4.3, 5.6, 7.2, 9.4, 12, 15.5, 20, 26)),
  DRR_3kHz = direct_LL_3k$direct - reverb_LL_3k$reverb
)

drr_df_WW <- data.frame(condicion = "WW",
  log_distancia = log(c(1.5, 2, 2.5, 3.3, 4.3, 5.6, 7.2, 9.4, 12, 15.5, 20, 26)),
  DRR_3kHz = direct_WW_3k$direct - reverb_WW_3k$reverb
)
drr_df_LW <- data.frame(condicion = "LW",
  log_distancia = log(c(1.5, 2, 2.5, 3.3, 4.3, 5.6, 7.2, 9.4, 12, 15.5, 20, 26)),
  DRR_3kHz = direct_LW_3k$direct - reverb_LW_3k$reverb
)
drr_df_WL <- data.frame(condicion = "WL",
  log_distancia = log(c(1.5, 2, 2.5, 3.3, 4.3, 5.6, 7.2, 9.4, 12, 15.5, 20, 26)),
  DRR_3kHz = direct_WL_3k$direct - reverb_WL_3k$reverb
)

drr_df <- bind_rows(drr_df_LL, drr_df_WW, drr_df_LW, drr_df_WL)
```

```{r}
grid_pred <- expand.grid(
  log_distancia = log(c(1.5, 2, 2.5, 3.3, 4.3, 5.6, 7.2, 9.4, 12, 15.5, 20, 26)),
  condicion = c("WW", "LL", "LW", "WL")
)

# 2. Predecir las respuestas esperadas del modelo (efectos fijos solamente)
grid_pred$respuesta_predicha <- predict(lmer.1k, newdata = grid_pred, re.form = NA)


# 4. Unir DRR y respuesta predicha
drr_respuestas <- left_join(drr_df, grid_pred, by = c("condicion", "log_distancia"))

# 5. Correlación por condición
library(ggpubr)

drr_respuestas %>%
  group_by(condicion) %>%
  summarise(cor = cor(DRR_3kHz, respuesta_predicha))
```